old_books = [
    "Seasons",
    "Owl Babies",
    "Where's My Teddy",
    "We're Going on a Bear Hunt",
    "Gruff the Grump",
    "The Owl's Lesson",
    "The Fox's Hiccups",
    "The Hedgehog's Balloon",
    "The Rescue Party",
    "The Cross Rabbit",
    "One Snowy Night",
    "After the Storm",
    "Can't You Sleep Little Bear",
    "All Year Round",
    "Father Christmas Needs A Wee",
    "I Love Christmas ",
    "The Polar Express",
    "How The Grinch Stole Christmas",
    "Santa is Coming to Devon",
    "The First Christmas",
    "A Letter to Santa",
    "The Night Before Christmas",
    "Jesus' Christmas Party",
    "One Starry Night",
    "The Christmas Story",
    "Ten in the Bed and Other Counting Rhymes",
    "Ten Tall Giraffes",
    "Elmer and Grandpa Eldo",
    "Elmer and the Stranger",
    "Elmer and Wilbur",
    "Elmer in the Snow",
    "Elmer and the Lost Teddy",
    "Elmer and the Wind",
    "Elmer on Stilts",
    "Elmer and Rose",
    "Cinder the Bubble-Blowing Dragon",
    "All For One",
    "Where's My Cuddle",
    "Sir Charlie Stinky Socks and the Really Big Adventure",
    "Who Will Sing My Puff-a-bye",
    "Harry and the Dinosaurs say Raahh!",
    "Harry and the Dinosaurs at the Museum",
    "Harry and the Bucketful of Dinosaurs",
    "Romp in the Swamp",
    "Harry and the Dinosaurs Go Wild",
    "Harry and the Robots",
    "Harry and the Dinosaurs go to School",
    "Monkey Puzzle",
    "What The Ladybird Heard",
    "The Snail and the Whale",
    "The Troll",
    "Tabby McTat",
    "Room on the Broom",
    "A Squash and a Squeeze",
    "Superworm",
    "The Gruffalo",
    "The Gruffalo's Child",
    "Charlie Cook's Favourite Book",
    "Night Monkey Day Monkey",
    "The Bumblebear",
    "Farmer Duck",
    "Each Peach Pear Plum",
    "Super Sid The Silly Sausage Dog",
    "Dinosaurs Love Underpants",
    "Kipper's Toybox",
    "Captain Duck",
    "You Choose",
    "We're Going On A Lion Hunt",
    "The Pirates Next Door",
    "The Jolly Postman or Other People's Letters",
    "Dogger",
    "How to Catch a Star",
    "Lost and Found",
    "Supertato Veggies Assemble",
    "The Lighthouse Keeper's Lunch",
    "Whatever Next!",
    "The Truth According to Arthur",
    "Kipper's A to Z",
    "The Cave",
    "Peace at Last",
    "All In One Piece",
    "Is It Betime Wibbly Pig",
    "Shark In The Dark",
    "Oi Dog!",
    "Caterpillar Butterfly",
    "Things You Should Know about Bugs",
    "Why Am I An Insect",
    "The Enormous Turnip",
    "The Very Lazy Ladybird",
    "The Teeny Weeny Tadpole",
    "Wiggling Worms At Work",
    "Mini Beasties",
    "Squash the Spider",
    "The Hungry Caterpillar",
    "Ten Wriggly, Wiggly Caterpillars",
    "The Very Busy Spider",
    "Little by Little",
    "The Bad-Tempered Ladybird",
    "Born to be a Butterfly",
    "Grandma Bird",
    "Grandad's Island",
    "The Storm Whale",
    "The Storm Whale In Winter",
    "The Dinosaur That Pooped Christmas",
    "The Snowiest Christmas Ever",
    "Lost in Snow",
    "Santa to the Rescue",
    "The Tree That's Meant To Be",
    "A Thing Called Snow",
    "When Granny Saved Christmas",
    "It's Christmas",
    "Careful Santa!",
    "The Christmas Extravaganza Hotel",
    "The Most Wonderful Gift In The World",
    "You Can't Take An Elephant On The Bus",
    "These Are Animals",
    "An Alphabet Of Stories",
    "Jasper's Jungle Journey",
    "Open Very Carefully, A Book With Bite!",
    "Mole Hill",
    "Boogie Bear",
    "The Animal Boogie",
    "Dogs Don't Do Ballet",
    "The Dinosaur Department Store",
    "The Owl Who Was Afraid Of The Dark",
    "The Duchess and Guy",
    "The Same But Different Too",
    "The Tiger Who Came To Tea",
    "There's A Monster In Your Book",
    "Oi Frog!",
    "The Runaway Pea",
    "Yoga Babies",
    "Scruffy Bear and the Six White Mice",
    "Mind Your Manners",
    "The Squirrels Who Squabbled",
    "The Way Home For Wolf",
    "Sing A Song Of Bottoms",
    "Bottoms Up!",
    "Knock Knock Alien",
    "Dragon Post",
    "I Am Amelia Earhart",
    "Wide-awake Hedgehog",
    "Little Monkey",
    "Knock Knock Dinosaur",
    "The Wheels on the Bus",
    "Knock Knock Pirate",
    "Lenny Makes A Wish",
    "She Rex",
    "Once Upon A Unicorn Horn",
    "The Book With No Pictures",
    "Zog and the Flying Doctors",
    "Cave Baby",
    "Tyrannosaurus Drip",
    "Sugarlump and the Unicorn",
    "Stick Man",
    "The Smartest Giant in Town",
    "The Rhyming Rabbit",
    "The Smeds and The Smoos",
    "Sharing A Shell",
    "The Princess and the Wizard",
    "The Singing Mermaid",
    "The Detective Dog",
    "Zog",
    "What The Ladybird Heard Next",
    "Princess Mirror-Belle And The Dragon Pox",
    "The Paper Dolls",
    "Supertato",
    "Gordon's Great Escape",
    "No-Bot",
    "Barry the Fish With Fingers and the Hairy Scary Monster",
    "Norman The Slug With The Silly Shell",
    "Barry The Fish With Fingers",
    "Doug The Bug That Went Boing",
    "I Need A Wee",
    "Keith The Cat With The Magic Hat",
    "All About Feelings",
    "Cinderella's Ballet Shoes",
    "Snow White, Star Striker",
    "Wake Up, Sleeping Beauty",
    "Who Will Save Us",
    "Hippo Owns Up",
    "Too Shy For Show And Tell",
    "Ruby's Worry",
    "Invisible Isabelle",
    "The Monstrous Tale of Celery Crumble",
    "Eleanor Won't Share",
    "Lion's in a Flap",
    "Elephant Learns to Share",
    "Jack Breaks The Beanstalk",
    "Monkey Needs to Listen",
    "Ravi's Roar",
    "The Little Bully",
    "Giraffe is Left Out",
    "Tiger Has a Tantrum",
    "The Enormous Crocodile",
    "The Ugly Duckling",
    "Goldilocks and the Three Bears",
    "The Gingerbread Man",
    "Little Red Riding Hood",
    "Jack and the Beanstalk",
    "The Three Little Pigs"
]